<?php

/**
 * Frozen ext-gtk 0.7.0 public static surfaces that microscrap/gtk must wrap.
 *
 * @return array<string, list<string>>
 */
return [
    'Gtk\\GTK\\Gtk' => [
        'gtkInitCheck',
        'gtkGetMajorVersion',
        'gtkGetMinorVersion',
        'gtkGetMicroVersion',
        'gtkGetBinaryAge',
    ],
    'Gtk\\GTK\\GtkError' => [
        'gtkLastMessage',
    ],
    'Gtk\\GTK\\Application\\GtkApplication' => [
        'gtkApplicationNew',
        'gtkApplicationRegister',
        'gtkApplicationRun',
        'gtkApplicationQuit',
        'gtkApplicationSetMenubar',
        'gtkApplicationSetAccelsForAction',
    ],
    'Gtk\\GTK\\Window\\GtkWindow' => [
        'gtkWindowNew',
        'gtkApplicationWindowNew',
        'gtkWindowSetTitle',
        'gtkWindowGetTitle',
        'gtkWindowSetDefaultSize',
        'gtkWindowGetDefaultSize',
        'gtkWindowSetChild',
        'gtkWindowGetChild',
        'gtkWindowPresent',
        'gtkWindowClose',
        'gtkWindowDestroy',
        'gtkWindowSetTitlebar',
        'gtkWindowGetTitlebar',
    ],
    'Gtk\\GTK\\Widget\\GtkWidget' => [
        'gtkWidgetSetVisible',
        'gtkWidgetGetVisible',
        'gtkWidgetSetHexpand',
        'gtkWidgetSetVexpand',
        'gtkWidgetSetHalign',
        'gtkWidgetSetValign',
        'gtkWidgetGetHalign',
        'gtkWidgetGetValign',
        'gtkWidgetSetSizeRequest',
        'gtkWidgetGetWidth',
        'gtkWidgetGetHeight',
        'gtkWidgetQueueDraw',
        'gtkWidgetAddTickCallback',
    ],
    'Gtk\\GTK\\Button\\GtkButton' => [
        'gtkButtonNew',
        'gtkButtonNewWithLabel',
        'gtkButtonSetLabel',
        'gtkButtonGetLabel',
    ],
    'Gtk\\GTK\\Label\\GtkLabel' => [
        'gtkLabelNew',
        'gtkLabelSetText',
        'gtkLabelGetText',
    ],
    'Gtk\\GTK\\Entry\\GtkEntry' => [
        'gtkEntryNew',
        'gtkEntrySetText',
        'gtkEntryGetText',
        'gtkEntrySetPlaceholderText',
        'gtkEntryGetPlaceholderText',
        'gtkEntrySetVisibility',
        'gtkEntryGetVisibility',
    ],
    'Gtk\\GTK\\CheckButton\\GtkCheckButton' => [
        'gtkCheckButtonNew',
        'gtkCheckButtonNewWithLabel',
        'gtkCheckButtonSetLabel',
        'gtkCheckButtonGetLabel',
        'gtkCheckButtonSetActive',
        'gtkCheckButtonGetActive',
    ],
    'Gtk\\GTK\\GtkSwitch\\GtkSwitch' => [
        'gtkSwitchNew',
        'gtkSwitchSetActive',
        'gtkSwitchGetActive',
    ],
    'Gtk\\GTK\\Image\\GtkImage' => [
        'gtkImageNew',
        'gtkImageNewFromFile',
        'gtkImageSetFromFile',
        'gtkImageSetFromIconName',
        'gtkImageClear',
        'gtkImageSetPixelSize',
    ],
    'Gtk\\GTK\\Picture\\GtkPicture' => [
        'gtkPictureNew',
        'gtkPictureNewForFilename',
        'gtkPictureSetFilename',
        'gtkPictureSetCanShrink',
    ],
    'Gtk\\GTK\\Spinner\\GtkSpinner' => [
        'gtkSpinnerNew',
        'gtkSpinnerStart',
        'gtkSpinnerStop',
        'gtkSpinnerSetSpinning',
        'gtkSpinnerGetSpinning',
    ],
    'Gtk\\GTK\\ProgressBar\\GtkProgressBar' => [
        'gtkProgressBarNew',
        'gtkProgressBarSetFraction',
        'gtkProgressBarGetFraction',
        'gtkProgressBarSetText',
        'gtkProgressBarGetText',
        'gtkProgressBarSetShowText',
        'gtkProgressBarPulse',
    ],
    'Gtk\\GTK\\Separator\\GtkSeparator' => [
        'gtkSeparatorNew',
    ],
    'Gtk\\GTK\\PasswordEntry\\GtkPasswordEntry' => [
        'gtkPasswordEntryNew',
        'gtkPasswordEntrySetText',
        'gtkPasswordEntryGetText',
        'gtkPasswordEntrySetShowPeekIcon',
        'gtkPasswordEntryGetShowPeekIcon',
    ],
    'Gtk\\GTK\\TextView\\GtkTextView' => [
        'gtkTextViewNew',
        'gtkTextViewGetBuffer',
        'gtkTextViewSetText',
        'gtkTextViewGetText',
        'gtkTextViewSetEditable',
        'gtkTextViewGetEditable',
        'gtkTextViewSetWrapMode',
        'gtkTextViewGetWrapMode',
    ],
    'Gtk\\GTK\\ToggleButton\\GtkToggleButton' => [
        'gtkToggleButtonNew',
        'gtkToggleButtonNewWithLabel',
        'gtkToggleButtonSetActive',
        'gtkToggleButtonGetActive',
        'gtkToggleButtonSetLabel',
        'gtkToggleButtonGetLabel',
    ],
    'Gtk\\GTK\\SpinButton\\GtkSpinButton' => [
        'gtkSpinButtonNewWithRange',
        'gtkSpinButtonSetValue',
        'gtkSpinButtonGetValue',
        'gtkSpinButtonGetValueAsInt',
        'gtkSpinButtonSetDigits',
    ],
    'Gtk\\GTK\\Scale\\GtkScale' => [
        'gtkScaleNewWithRange',
        'gtkScaleSetValue',
        'gtkScaleGetValue',
        'gtkScaleSetDrawValue',
        'gtkScaleSetDigits',
    ],
    'Gtk\\GTK\\DropDown\\GtkDropDown' => [
        'gtkDropDownNewFromStrings',
        'gtkDropDownSetSelected',
        'gtkDropDownGetSelected',
    ],
    'Gtk\\GTK\\SearchEntry\\GtkSearchEntry' => [
        'gtkSearchEntryNew',
        'gtkSearchEntrySetText',
        'gtkSearchEntryGetText',
    ],
    'Gtk\\GTK\\HeaderBar\\GtkHeaderBar' => [
        'gtkHeaderBarNew',
        'gtkHeaderBarSetTitleWidget',
        'gtkHeaderBarGetTitleWidget',
        'gtkHeaderBarPackStart',
        'gtkHeaderBarPackEnd',
        'gtkHeaderBarRemove',
        'gtkHeaderBarSetShowTitleButtons',
        'gtkHeaderBarGetShowTitleButtons',
    ],
    'Gtk\\GTK\\MenuButton\\GtkMenuButton' => [
        'gtkMenuButtonNew',
        'gtkMenuButtonSetLabel',
        'gtkMenuButtonGetLabel',
        'gtkMenuButtonSetPopover',
        'gtkMenuButtonGetPopover',
        'gtkMenuButtonSetMenuModel',
        'gtkMenuButtonPopup',
        'gtkMenuButtonPopdown',
    ],
    'Gtk\\GTK\\Popover\\GtkPopover' => [
        'gtkPopoverNew',
        'gtkPopoverSetChild',
        'gtkPopoverGetChild',
        'gtkPopoverPopup',
        'gtkPopoverPopdown',
        'gtkPopoverSetAutohide',
    ],
    'Gtk\\GTK\\PopoverMenu\\GtkPopoverMenu' => [
        'gtkPopoverMenuNewFromModel',
    ],
    'Gtk\\GTK\\PopoverMenuBar\\GtkPopoverMenuBar' => [
        'gtkPopoverMenuBarNewFromModel',
    ],
    'Gtk\\GTK\\ScrolledWindow\\GtkScrolledWindow' => [
        'gtkScrolledWindowNew',
        'gtkScrolledWindowSetChild',
        'gtkScrolledWindowGetChild',
        'gtkScrolledWindowSetPolicy',
        'gtkScrolledWindowSetMinContentHeight',
        'gtkScrolledWindowSetMinContentWidth',
    ],
    'Gtk\\GTK\\Notebook\\GtkNotebook' => [
        'gtkNotebookNew',
        'gtkNotebookAppendPage',
        'gtkNotebookRemovePage',
        'gtkNotebookGetNPages',
        'gtkNotebookSetCurrentPage',
        'gtkNotebookGetCurrentPage',
        'gtkNotebookSetTabLabelText',
    ],
    'Gtk\\GTK\\Stack\\GtkStack' => [
        'gtkStackNew',
        'gtkStackAddChild',
        'gtkStackAddTitled',
        'gtkStackRemove',
        'gtkStackSetVisibleChild',
        'gtkStackGetVisibleChild',
        'gtkStackSetVisibleChildName',
        'gtkStackGetVisibleChildName',
    ],
    'Gtk\\GTK\\Paned\\GtkPaned' => [
        'gtkPanedNew',
        'gtkPanedSetStartChild',
        'gtkPanedSetEndChild',
        'gtkPanedGetStartChild',
        'gtkPanedGetEndChild',
        'gtkPanedSetPosition',
        'gtkPanedGetPosition',
    ],
    'Gtk\\GTK\\Grid\\GtkGrid' => [
        'gtkGridNew',
        'gtkGridAttach',
        'gtkGridRemove',
        'gtkGridSetRowSpacing',
        'gtkGridSetColumnSpacing',
        'gtkGridSetRowHomogeneous',
        'gtkGridSetColumnHomogeneous',
    ],
    'Gtk\\GTK\\CenterBox\\GtkCenterBox' => [
        'gtkCenterBoxNew',
        'gtkCenterBoxSetStartWidget',
        'gtkCenterBoxSetCenterWidget',
        'gtkCenterBoxSetEndWidget',
        'gtkCenterBoxGetStartWidget',
        'gtkCenterBoxGetCenterWidget',
        'gtkCenterBoxGetEndWidget',
    ],
    'Gtk\\GTK\\Overlay\\GtkOverlay' => [
        'gtkOverlayNew',
        'gtkOverlaySetChild',
        'gtkOverlayGetChild',
        'gtkOverlayAddOverlay',
        'gtkOverlayRemoveOverlay',
    ],
    'Gtk\\GTK\\ListBox\\GtkListBox' => [
        'gtkListBoxNew',
        'gtkListBoxAppend',
        'gtkListBoxRemove',
        'gtkListBoxGetSelectedRow',
        'gtkListBoxSelectRow',
        'gtkListBoxGetRowAtIndex',
        'gtkListBoxRowGetIndex',
        'gtkListBoxRowGetChild',
    ],
    'Gtk\\GTK\\StringList\\GtkStringList' => [
        'gtkStringListNew',
        'gtkStringListAppend',
        'gtkStringListRemove',
        'gtkStringListGetString',
        'gtkStringListGetNItems',
        'gtkStringObjectGetString',
    ],
    'Gtk\\GTK\\SingleSelection\\GtkSingleSelection' => [
        'gtkSingleSelectionNew',
        'gtkSingleSelectionSetSelected',
        'gtkSingleSelectionGetSelected',
        'gtkSingleSelectionGetModel',
    ],
    'Gtk\\GTK\\ListItem\\GtkListItem' => [
        'gtkSignalListItemFactoryNew',
        'gtkListItemSetChild',
        'gtkListItemGetChild',
        'gtkListItemGetItem',
        'gtkListItemGetPosition',
    ],
    'Gtk\\GTK\\ListView\\GtkListView' => [
        'gtkListViewNew',
        'gtkListViewSetModel',
        'gtkListViewGetModel',
        'gtkListViewSetFactory',
    ],
    'Gtk\\GTK\\AlertDialog\\GtkAlertDialog' => [
        'gtkAlertDialogNew',
        'gtkAlertDialogSetDetail',
        'gtkAlertDialogSetButtons',
        'gtkAlertDialogSetModal',
        'gtkAlertDialogShow',
        'gtkAlertDialogChoose',
    ],
    'Gtk\\GTK\\FileDialog\\GtkFileDialog' => [
        'gtkFileDialogNew',
        'gtkFileDialogSetTitle',
        'gtkFileDialogGetTitle',
        'gtkFileDialogSetInitialName',
        'gtkFileDialogOpen',
        'gtkFileDialogSave',
        'gtkFileDialogSelectFolder',
    ],
    'Gtk\\GTK\\ColorDialog\\GtkColorDialog' => [
        'gtkColorDialogNew',
        'gtkColorDialogSetTitle',
        'gtkColorDialogSetModal',
        'gtkColorDialogChooseRgba',
    ],
    'Gtk\\GTK\\FontDialog\\GtkFontDialog' => [
        'gtkFontDialogNew',
        'gtkFontDialogSetTitle',
        'gtkFontDialogSetModal',
        'gtkFontDialogChooseFont',
    ],
    'Gtk\\GTK\\GMenu\\GMenu' => [
        'gMenuNew',
        'gMenuAppend',
        'gMenuAppendSection',
        'gMenuAppendSubmenu',
        'gMenuFreeze',
    ],
    'Gtk\\GTK\\GSimpleAction\\GSimpleAction' => [
        'gSimpleActionNew',
        'gActionMapAddAction',
        'gSimpleActionSetEnabled',
    ],
    'Gtk\\GTK\\Box\\GtkBox' => [
        'gtkBoxNew',
        'gtkBoxAppend',
        'gtkBoxRemove',
        'gtkBoxSetSpacing',
    ],
    'Gtk\\GTK\\GpuPane\\GtkGpuPane' => [
        'gtkGpuPaneNew',
        'gtkGpuPaneNative',
    ],
    'Gtk\\GTK\\GLArea\\GtkGLArea' => [
        'gtkGLAreaNew',
        'gtkGLAreaMakeCurrent',
        'gtkGLAreaQueueRender',
        'gtkGLAreaSetAutoRender',
        'gtkGLAreaGetError',
    ],
    'Gtk\\GTK\\GtkGLib' => [
        'gObjectRef',
        'gObjectUnref',
        'gSignalConnect',
        'gMainContextDefault',
        'gMainContextIteration',
    ],
];
