<?php

namespace DeptOfScrapyardRobotics\Tests\Support;

/**
 * Maps Gtk\GTK\* camelCase methods to C ABI helper names (gtk_* / g_*).
 */
final class HelperNames
{
    /**
     * @var array<string, array<string, string>>
     */
    private const MAP = [
        'Gtk\\GTK\\Gtk' => [
            'gtkInitCheck' => 'gtk_init_check',
            'gtkGetMajorVersion' => 'gtk_get_major_version',
            'gtkGetMinorVersion' => 'gtk_get_minor_version',
            'gtkGetMicroVersion' => 'gtk_get_micro_version',
            'gtkGetBinaryAge' => 'gtk_get_binary_age',
        ],
        'Gtk\\GTK\\GtkError' => [
            'gtkLastMessage' => 'gtk_last_message',
        ],
        'Gtk\\GTK\\Application\\GtkApplication' => [
            'gtkApplicationNew' => 'gtk_application_new',
            'gtkApplicationRegister' => 'g_application_register',
            'gtkApplicationRun' => 'gtk_application_run',
            'gtkApplicationQuit' => 'gtk_application_quit',
            'gtkApplicationSetMenubar' => 'gtk_application_set_menubar',
            'gtkApplicationSetAccelsForAction' => 'gtk_application_set_accels_for_action',
        ],
        'Gtk\\GTK\\Window\\GtkWindow' => [
            'gtkWindowNew' => 'gtk_window_new',
            'gtkApplicationWindowNew' => 'gtk_application_window_new',
            'gtkWindowSetTitle' => 'gtk_window_set_title',
            'gtkWindowGetTitle' => 'gtk_window_get_title',
            'gtkWindowSetDefaultSize' => 'gtk_window_set_default_size',
            'gtkWindowGetDefaultSize' => 'gtk_window_get_default_size',
            'gtkWindowSetChild' => 'gtk_window_set_child',
            'gtkWindowGetChild' => 'gtk_window_get_child',
            'gtkWindowPresent' => 'gtk_window_present',
            'gtkWindowClose' => 'gtk_window_close',
            'gtkWindowDestroy' => 'gtk_window_destroy',
            'gtkWindowSetTitlebar' => 'gtk_window_set_titlebar',
            'gtkWindowGetTitlebar' => 'gtk_window_get_titlebar',
        ],
        'Gtk\\GTK\\Widget\\GtkWidget' => [
            'gtkWidgetSetVisible' => 'gtk_widget_set_visible',
            'gtkWidgetGetVisible' => 'gtk_widget_get_visible',
            'gtkWidgetSetHexpand' => 'gtk_widget_set_hexpand',
            'gtkWidgetSetVexpand' => 'gtk_widget_set_vexpand',
            'gtkWidgetSetHalign' => 'gtk_widget_set_halign',
            'gtkWidgetSetValign' => 'gtk_widget_set_valign',
            'gtkWidgetGetHalign' => 'gtk_widget_get_halign',
            'gtkWidgetGetValign' => 'gtk_widget_get_valign',
            'gtkWidgetSetSizeRequest' => 'gtk_widget_set_size_request',
            'gtkWidgetGetWidth' => 'gtk_widget_get_width',
            'gtkWidgetGetHeight' => 'gtk_widget_get_height',
            'gtkWidgetQueueDraw' => 'gtk_widget_queue_draw',
            'gtkWidgetAddTickCallback' => 'gtk_widget_add_tick_callback',
            'gtkWidgetApplyCss' => 'gtk_widget_apply_css',
        ],
        'Gtk\\GTK\\Button\\GtkButton' => [
            'gtkButtonNew' => 'gtk_button_new',
            'gtkButtonNewWithLabel' => 'gtk_button_new_with_label',
            'gtkButtonSetLabel' => 'gtk_button_set_label',
            'gtkButtonGetLabel' => 'gtk_button_get_label',
        ],
        'Gtk\\GTK\\Label\\GtkLabel' => [
            'gtkLabelNew' => 'gtk_label_new',
            'gtkLabelSetText' => 'gtk_label_set_text',
            'gtkLabelGetText' => 'gtk_label_get_text',
            'gtkLabelSetXalign' => 'gtk_label_set_xalign',
        ],
        'Gtk\\GTK\\Entry\\GtkEntry' => [
            'gtkEntryNew' => 'gtk_entry_new',
            'gtkEntrySetText' => 'gtk_entry_set_text',
            'gtkEntryGetText' => 'gtk_entry_get_text',
            'gtkEntrySetPlaceholderText' => 'gtk_entry_set_placeholder_text',
            'gtkEntryGetPlaceholderText' => 'gtk_entry_get_placeholder_text',
            'gtkEntrySetVisibility' => 'gtk_entry_set_visibility',
            'gtkEntryGetVisibility' => 'gtk_entry_get_visibility',
        ],
        'Gtk\\GTK\\CheckButton\\GtkCheckButton' => [
            'gtkCheckButtonNew' => 'gtk_check_button_new',
            'gtkCheckButtonNewWithLabel' => 'gtk_check_button_new_with_label',
            'gtkCheckButtonSetLabel' => 'gtk_check_button_set_label',
            'gtkCheckButtonGetLabel' => 'gtk_check_button_get_label',
            'gtkCheckButtonSetActive' => 'gtk_check_button_set_active',
            'gtkCheckButtonGetActive' => 'gtk_check_button_get_active',
            'gtkCheckButtonSetGroup' => 'gtk_check_button_set_group',
        ],
        'Gtk\\GTK\\GtkSwitch\\GtkSwitch' => [
            'gtkSwitchNew' => 'gtk_switch_new',
            'gtkSwitchSetActive' => 'gtk_switch_set_active',
            'gtkSwitchGetActive' => 'gtk_switch_get_active',
        ],
        'Gtk\\GTK\\Image\\GtkImage' => [
            'gtkImageNew' => 'gtk_image_new',
            'gtkImageNewFromFile' => 'gtk_image_new_from_file',
            'gtkImageSetFromFile' => 'gtk_image_set_from_file',
            'gtkImageSetFromIconName' => 'gtk_image_set_from_icon_name',
            'gtkImageClear' => 'gtk_image_clear',
            'gtkImageSetPixelSize' => 'gtk_image_set_pixel_size',
        ],
        'Gtk\\GTK\\Picture\\GtkPicture' => [
            'gtkPictureNew' => 'gtk_picture_new',
            'gtkPictureNewForFilename' => 'gtk_picture_new_for_filename',
            'gtkPictureSetFilename' => 'gtk_picture_set_filename',
            'gtkPictureSetCanShrink' => 'gtk_picture_set_can_shrink',
        ],
        'Gtk\\GTK\\Spinner\\GtkSpinner' => [
            'gtkSpinnerNew' => 'gtk_spinner_new',
            'gtkSpinnerStart' => 'gtk_spinner_start',
            'gtkSpinnerStop' => 'gtk_spinner_stop',
            'gtkSpinnerSetSpinning' => 'gtk_spinner_set_spinning',
            'gtkSpinnerGetSpinning' => 'gtk_spinner_get_spinning',
        ],
        'Gtk\\GTK\\ProgressBar\\GtkProgressBar' => [
            'gtkProgressBarNew' => 'gtk_progress_bar_new',
            'gtkProgressBarSetFraction' => 'gtk_progress_bar_set_fraction',
            'gtkProgressBarGetFraction' => 'gtk_progress_bar_get_fraction',
            'gtkProgressBarSetText' => 'gtk_progress_bar_set_text',
            'gtkProgressBarGetText' => 'gtk_progress_bar_get_text',
            'gtkProgressBarSetShowText' => 'gtk_progress_bar_set_show_text',
            'gtkProgressBarPulse' => 'gtk_progress_bar_pulse',
        ],
        'Gtk\\GTK\\Separator\\GtkSeparator' => [
            'gtkSeparatorNew' => 'gtk_separator_new',
        ],
        'Gtk\\GTK\\PasswordEntry\\GtkPasswordEntry' => [
            'gtkPasswordEntryNew' => 'gtk_password_entry_new',
            'gtkPasswordEntrySetText' => 'gtk_password_entry_set_text',
            'gtkPasswordEntryGetText' => 'gtk_password_entry_get_text',
            'gtkPasswordEntrySetShowPeekIcon' => 'gtk_password_entry_set_show_peek_icon',
            'gtkPasswordEntryGetShowPeekIcon' => 'gtk_password_entry_get_show_peek_icon',
        ],
        'Gtk\\GTK\\TextView\\GtkTextView' => [
            'gtkTextViewNew' => 'gtk_text_view_new',
            'gtkTextViewGetBuffer' => 'gtk_text_view_get_buffer',
            'gtkTextViewSetText' => 'gtk_text_view_set_text',
            'gtkTextViewGetText' => 'gtk_text_view_get_text',
            'gtkTextViewSetEditable' => 'gtk_text_view_set_editable',
            'gtkTextViewGetEditable' => 'gtk_text_view_get_editable',
            'gtkTextViewSetWrapMode' => 'gtk_text_view_set_wrap_mode',
            'gtkTextViewGetWrapMode' => 'gtk_text_view_get_wrap_mode',
        ],
        'Gtk\\GTK\\ToggleButton\\GtkToggleButton' => [
            'gtkToggleButtonNew' => 'gtk_toggle_button_new',
            'gtkToggleButtonNewWithLabel' => 'gtk_toggle_button_new_with_label',
            'gtkToggleButtonSetActive' => 'gtk_toggle_button_set_active',
            'gtkToggleButtonGetActive' => 'gtk_toggle_button_get_active',
            'gtkToggleButtonSetLabel' => 'gtk_toggle_button_set_label',
            'gtkToggleButtonGetLabel' => 'gtk_toggle_button_get_label',
        ],
        'Gtk\\GTK\\SpinButton\\GtkSpinButton' => [
            'gtkSpinButtonNewWithRange' => 'gtk_spin_button_new_with_range',
            'gtkSpinButtonSetValue' => 'gtk_spin_button_set_value',
            'gtkSpinButtonGetValue' => 'gtk_spin_button_get_value',
            'gtkSpinButtonGetValueAsInt' => 'gtk_spin_button_get_value_as_int',
            'gtkSpinButtonSetDigits' => 'gtk_spin_button_set_digits',
        ],
        'Gtk\\GTK\\Scale\\GtkScale' => [
            'gtkScaleNewWithRange' => 'gtk_scale_new_with_range',
            'gtkScaleSetValue' => 'gtk_scale_set_value',
            'gtkScaleGetValue' => 'gtk_scale_get_value',
            'gtkScaleSetDrawValue' => 'gtk_scale_set_draw_value',
            'gtkScaleSetDigits' => 'gtk_scale_set_digits',
        ],
        'Gtk\\GTK\\DropDown\\GtkDropDown' => [
            'gtkDropDownNewFromStrings' => 'gtk_drop_down_new_from_strings',
            'gtkDropDownSetSelected' => 'gtk_drop_down_set_selected',
            'gtkDropDownGetSelected' => 'gtk_drop_down_get_selected',
        ],
        'Gtk\\GTK\\SearchEntry\\GtkSearchEntry' => [
            'gtkSearchEntryNew' => 'gtk_search_entry_new',
            'gtkSearchEntrySetText' => 'gtk_search_entry_set_text',
            'gtkSearchEntryGetText' => 'gtk_search_entry_get_text',
        ],
        'Gtk\\GTK\\HeaderBar\\GtkHeaderBar' => [
            'gtkHeaderBarNew' => 'gtk_header_bar_new',
            'gtkHeaderBarSetTitleWidget' => 'gtk_header_bar_set_title_widget',
            'gtkHeaderBarGetTitleWidget' => 'gtk_header_bar_get_title_widget',
            'gtkHeaderBarPackStart' => 'gtk_header_bar_pack_start',
            'gtkHeaderBarPackEnd' => 'gtk_header_bar_pack_end',
            'gtkHeaderBarRemove' => 'gtk_header_bar_remove',
            'gtkHeaderBarSetShowTitleButtons' => 'gtk_header_bar_set_show_title_buttons',
            'gtkHeaderBarGetShowTitleButtons' => 'gtk_header_bar_get_show_title_buttons',
        ],
        'Gtk\\GTK\\MenuButton\\GtkMenuButton' => [
            'gtkMenuButtonNew' => 'gtk_menu_button_new',
            'gtkMenuButtonSetLabel' => 'gtk_menu_button_set_label',
            'gtkMenuButtonGetLabel' => 'gtk_menu_button_get_label',
            'gtkMenuButtonSetPopover' => 'gtk_menu_button_set_popover',
            'gtkMenuButtonGetPopover' => 'gtk_menu_button_get_popover',
            'gtkMenuButtonSetMenuModel' => 'gtk_menu_button_set_menu_model',
            'gtkMenuButtonPopup' => 'gtk_menu_button_popup',
            'gtkMenuButtonPopdown' => 'gtk_menu_button_popdown',
        ],
        'Gtk\\GTK\\Popover\\GtkPopover' => [
            'gtkPopoverNew' => 'gtk_popover_new',
            'gtkPopoverSetChild' => 'gtk_popover_set_child',
            'gtkPopoverGetChild' => 'gtk_popover_get_child',
            'gtkPopoverPopup' => 'gtk_popover_popup',
            'gtkPopoverPopdown' => 'gtk_popover_popdown',
            'gtkPopoverSetAutohide' => 'gtk_popover_set_autohide',
        ],
        'Gtk\\GTK\\PopoverMenu\\GtkPopoverMenu' => [
            'gtkPopoverMenuNewFromModel' => 'gtk_popover_menu_new_from_model',
        ],
        'Gtk\\GTK\\PopoverMenuBar\\GtkPopoverMenuBar' => [
            'gtkPopoverMenuBarNewFromModel' => 'gtk_popover_menu_bar_new_from_model',
        ],
        'Gtk\\GTK\\ScrolledWindow\\GtkScrolledWindow' => [
            'gtkScrolledWindowNew' => 'gtk_scrolled_window_new',
            'gtkScrolledWindowSetChild' => 'gtk_scrolled_window_set_child',
            'gtkScrolledWindowGetChild' => 'gtk_scrolled_window_get_child',
            'gtkScrolledWindowSetPolicy' => 'gtk_scrolled_window_set_policy',
            'gtkScrolledWindowSetMinContentHeight' => 'gtk_scrolled_window_set_min_content_height',
            'gtkScrolledWindowSetMinContentWidth' => 'gtk_scrolled_window_set_min_content_width',
        ],
        'Gtk\\GTK\\Notebook\\GtkNotebook' => [
            'gtkNotebookNew' => 'gtk_notebook_new',
            'gtkNotebookAppendPage' => 'gtk_notebook_append_page',
            'gtkNotebookRemovePage' => 'gtk_notebook_remove_page',
            'gtkNotebookGetNPages' => 'gtk_notebook_get_n_pages',
            'gtkNotebookSetCurrentPage' => 'gtk_notebook_set_current_page',
            'gtkNotebookGetCurrentPage' => 'gtk_notebook_get_current_page',
            'gtkNotebookSetTabLabelText' => 'gtk_notebook_set_tab_label_text',
        ],
        'Gtk\\GTK\\Stack\\GtkStack' => [
            'gtkStackNew' => 'gtk_stack_new',
            'gtkStackAddChild' => 'gtk_stack_add_child',
            'gtkStackAddTitled' => 'gtk_stack_add_titled',
            'gtkStackRemove' => 'gtk_stack_remove',
            'gtkStackSetVisibleChild' => 'gtk_stack_set_visible_child',
            'gtkStackGetVisibleChild' => 'gtk_stack_get_visible_child',
            'gtkStackSetVisibleChildName' => 'gtk_stack_set_visible_child_name',
            'gtkStackGetVisibleChildName' => 'gtk_stack_get_visible_child_name',
        ],
        'Gtk\\GTK\\Paned\\GtkPaned' => [
            'gtkPanedNew' => 'gtk_paned_new',
            'gtkPanedSetStartChild' => 'gtk_paned_set_start_child',
            'gtkPanedSetEndChild' => 'gtk_paned_set_end_child',
            'gtkPanedGetStartChild' => 'gtk_paned_get_start_child',
            'gtkPanedGetEndChild' => 'gtk_paned_get_end_child',
            'gtkPanedSetPosition' => 'gtk_paned_set_position',
            'gtkPanedGetPosition' => 'gtk_paned_get_position',
        ],
        'Gtk\\GTK\\Grid\\GtkGrid' => [
            'gtkGridNew' => 'gtk_grid_new',
            'gtkGridAttach' => 'gtk_grid_attach',
            'gtkGridRemove' => 'gtk_grid_remove',
            'gtkGridSetRowSpacing' => 'gtk_grid_set_row_spacing',
            'gtkGridSetColumnSpacing' => 'gtk_grid_set_column_spacing',
            'gtkGridSetRowHomogeneous' => 'gtk_grid_set_row_homogeneous',
            'gtkGridSetColumnHomogeneous' => 'gtk_grid_set_column_homogeneous',
        ],
        'Gtk\\GTK\\Fixed\\GtkFixed' => [
            'gtkFixedNew' => 'gtk_fixed_new',
            'gtkFixedPut' => 'gtk_fixed_put',
            'gtkFixedMove' => 'gtk_fixed_move',
            'gtkFixedRemove' => 'gtk_fixed_remove',
            'gtkFixedGetChildPosition' => 'gtk_fixed_get_child_position',
        ],
        'Gtk\\GTK\\CenterBox\\GtkCenterBox' => [
            'gtkCenterBoxNew' => 'gtk_center_box_new',
            'gtkCenterBoxSetStartWidget' => 'gtk_center_box_set_start_widget',
            'gtkCenterBoxSetCenterWidget' => 'gtk_center_box_set_center_widget',
            'gtkCenterBoxSetEndWidget' => 'gtk_center_box_set_end_widget',
            'gtkCenterBoxGetStartWidget' => 'gtk_center_box_get_start_widget',
            'gtkCenterBoxGetCenterWidget' => 'gtk_center_box_get_center_widget',
            'gtkCenterBoxGetEndWidget' => 'gtk_center_box_get_end_widget',
        ],
        'Gtk\\GTK\\Overlay\\GtkOverlay' => [
            'gtkOverlayNew' => 'gtk_overlay_new',
            'gtkOverlaySetChild' => 'gtk_overlay_set_child',
            'gtkOverlayGetChild' => 'gtk_overlay_get_child',
            'gtkOverlayAddOverlay' => 'gtk_overlay_add_overlay',
            'gtkOverlayRemoveOverlay' => 'gtk_overlay_remove_overlay',
        ],
        'Gtk\\GTK\\ListBox\\GtkListBox' => [
            'gtkListBoxNew' => 'gtk_list_box_new',
            'gtkListBoxAppend' => 'gtk_list_box_append',
            'gtkListBoxRemove' => 'gtk_list_box_remove',
            'gtkListBoxGetSelectedRow' => 'gtk_list_box_get_selected_row',
            'gtkListBoxSelectRow' => 'gtk_list_box_select_row',
            'gtkListBoxGetRowAtIndex' => 'gtk_list_box_get_row_at_index',
            'gtkListBoxRowGetIndex' => 'gtk_list_box_row_get_index',
            'gtkListBoxRowGetChild' => 'gtk_list_box_row_get_child',
        ],
        'Gtk\\GTK\\StringList\\GtkStringList' => [
            'gtkStringListNew' => 'gtk_string_list_new',
            'gtkStringListAppend' => 'gtk_string_list_append',
            'gtkStringListRemove' => 'gtk_string_list_remove',
            'gtkStringListGetString' => 'gtk_string_list_get_string',
            'gtkStringListGetNItems' => 'gtk_string_list_get_n_items',
            'gtkStringObjectGetString' => 'gtk_string_object_get_string',
        ],
        'Gtk\\GTK\\SingleSelection\\GtkSingleSelection' => [
            'gtkSingleSelectionNew' => 'gtk_single_selection_new',
            'gtkSingleSelectionSetSelected' => 'gtk_single_selection_set_selected',
            'gtkSingleSelectionGetSelected' => 'gtk_single_selection_get_selected',
            'gtkSingleSelectionGetModel' => 'gtk_single_selection_get_model',
        ],
        'Gtk\\GTK\\ListItem\\GtkListItem' => [
            'gtkSignalListItemFactoryNew' => 'gtk_signal_list_item_factory_new',
            'gtkListItemSetChild' => 'gtk_list_item_set_child',
            'gtkListItemGetChild' => 'gtk_list_item_get_child',
            'gtkListItemGetItem' => 'gtk_list_item_get_item',
            'gtkListItemGetPosition' => 'gtk_list_item_get_position',
        ],
        'Gtk\\GTK\\ListView\\GtkListView' => [
            'gtkListViewNew' => 'gtk_list_view_new',
            'gtkListViewSetModel' => 'gtk_list_view_set_model',
            'gtkListViewGetModel' => 'gtk_list_view_get_model',
            'gtkListViewSetFactory' => 'gtk_list_view_set_factory',
        ],
        'Gtk\\GTK\\AlertDialog\\GtkAlertDialog' => [
            'gtkAlertDialogNew' => 'gtk_alert_dialog_new',
            'gtkAlertDialogSetDetail' => 'gtk_alert_dialog_set_detail',
            'gtkAlertDialogSetButtons' => 'gtk_alert_dialog_set_buttons',
            'gtkAlertDialogSetModal' => 'gtk_alert_dialog_set_modal',
            'gtkAlertDialogShow' => 'gtk_alert_dialog_show',
            'gtkAlertDialogChoose' => 'gtk_alert_dialog_choose',
        ],
        'Gtk\\GTK\\FileDialog\\GtkFileDialog' => [
            'gtkFileDialogNew' => 'gtk_file_dialog_new',
            'gtkFileDialogSetTitle' => 'gtk_file_dialog_set_title',
            'gtkFileDialogGetTitle' => 'gtk_file_dialog_get_title',
            'gtkFileDialogSetInitialName' => 'gtk_file_dialog_set_initial_name',
            'gtkFileDialogOpen' => 'gtk_file_dialog_open',
            'gtkFileDialogSave' => 'gtk_file_dialog_save',
            'gtkFileDialogSelectFolder' => 'gtk_file_dialog_select_folder',
        ],
        'Gtk\\GTK\\ColorDialog\\GtkColorDialog' => [
            'gtkColorDialogNew' => 'gtk_color_dialog_new',
            'gtkColorDialogSetTitle' => 'gtk_color_dialog_set_title',
            'gtkColorDialogSetModal' => 'gtk_color_dialog_set_modal',
            'gtkColorDialogChooseRgba' => 'gtk_color_dialog_choose_rgba',
        ],
        'Gtk\\GTK\\GMenu\\GMenu' => [
            'gMenuNew' => 'g_menu_new',
            'gMenuAppend' => 'g_menu_append',
            'gMenuAppendSection' => 'g_menu_append_section',
            'gMenuAppendSubmenu' => 'g_menu_append_submenu',
            'gMenuFreeze' => 'g_menu_freeze',
        ],
        'Gtk\\GTK\\GSimpleAction\\GSimpleAction' => [
            'gSimpleActionNew' => 'g_simple_action_new',
            'gActionMapAddAction' => 'g_action_map_add_action',
            'gSimpleActionSetEnabled' => 'g_simple_action_set_enabled',
        ],
        'Gtk\\GTK\\FontDialog\\GtkFontDialog' => [
            'gtkFontDialogNew' => 'gtk_font_dialog_new',
            'gtkFontDialogSetTitle' => 'gtk_font_dialog_set_title',
            'gtkFontDialogSetModal' => 'gtk_font_dialog_set_modal',
            'gtkFontDialogChooseFont' => 'gtk_font_dialog_choose_font',
        ],
        'Gtk\\GTK\\Box\\GtkBox' => [
            'gtkBoxNew' => 'gtk_box_new',
            'gtkBoxAppend' => 'gtk_box_append',
            'gtkBoxRemove' => 'gtk_box_remove',
            'gtkBoxSetSpacing' => 'gtk_box_set_spacing',
        ],
        'Gtk\\GTK\\GpuPane\\GtkGpuPane' => [
            'gtkGpuPaneNew' => 'gtk_gpu_pane_new',
            'gtkGpuPaneNative' => 'gtk_gpu_pane_native',
        ],
        'Gtk\\GTK\\GLArea\\GtkGLArea' => [
            'gtkGLAreaNew' => 'gtk_gl_area_new',
            'gtkGLAreaMakeCurrent' => 'gtk_gl_area_make_current',
            'gtkGLAreaQueueRender' => 'gtk_gl_area_queue_render',
            'gtkGLAreaSetAutoRender' => 'gtk_gl_area_set_auto_render',
            'gtkGLAreaGetError' => 'gtk_gl_area_get_error',
        ],
        'Gtk\\GTK\\GtkGLib' => [
            'gObjectRef' => 'g_object_ref',
            'gObjectUnref' => 'g_object_unref',
            'gSignalConnect' => 'g_signal_connect',
            'gMainContextDefault' => 'g_main_context_default',
            'gMainContextIteration' => 'g_main_context_iteration',
        ],
    ];

    public static function for(string $extensionClass, string $method): string
    {
        if (! isset(self::MAP[$extensionClass][$method])) {
            throw new \InvalidArgumentException("No helper mapping for {$extensionClass}::{$method}");
        }

        return self::MAP[$extensionClass][$method];
    }
}
